### ISSUE TITLE
Duration Value

### ISSUE THREAD

**Issue by lakhsmi** [kshaaban-/ionic-durationpicker#3]
Hello,

How do I get once the value is set from the duration widget into controller. I kept the widget in my form while submitting I was unable to get the Duration value and also I did not find the any callback function for set method if we have callback function then it is helpful other things . What do you say ?

**Comment by webdevius** [comment]
@lakhsmi The directive binds the duration value to whatever variable name you pass in the `idp-output` attribute. It will give out the value in seconds.

**Comment by lakhsmi** [comment]
@kshaaban- OK. Here is my issues on initialization I set   the value $scope.mileRunDuration = 10 i,e it shows 0:10 as duration time later on I update the to 1:45 as duration time when try to print the   $scope.mileRunDuration it is getting the old one not updated one in the controller any thing wrong with me.

**Comment by webdevius** [comment]
@lakhsmi No, nothing is wrong with you - As a matter of fact, when I wrote the docs/demo, I missed the fact that two-way data binding between parent and children scopes on primitive data types (the duration in seconds is an integer) doesn't work as one would expect .

Try passing an object property instead of a scope variable and things should work just fine. i.e.

``` javascript
// Controller:
$scope.durations = {
    mileRun: 10
}

// Template:
<ionic-durationpicker idp-label="Example 1" idp-output="durations.mileRun">
</ionic-durationpicker>
```

I'll update the docs to reflect that accordingly.
Thank you for bringing that up 👍
